language: java
install: true

jdk:
- openjdk10

before_script:
- cd owl-tools

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      repo: opencaesar/owl-tools
      branch: master